In [1]:
import numpy as np

# Tạo mảng
a = np.array([1,4,5])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 4 5]
4


In [2]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [15, 20, 31], [7, 9, 10]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[ 1  2  3]
 [15 20 31]
 [ 7  9 10]]
31


In [3]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(4)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(6)
print(a)

# Tạo mảng
a = np.empty(6)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(50)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 20, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 0.  5. 10. 15. 20.]


array([1, 1, 1, 1, 1])

In [4]:
# Thêm, xóa, sắp xếp mảng

# Tạo mảng ban đầu
arr = np.array([3, 15, 2, 10, 30, 21, 50, 16])
print(arr)

# Sắp xếp
arr = np.sort(arr)
print(arr)

# Sắp xếp ngược
arr = np.sort(arr)[::-3]
print(arr)

# Thêm phần tử vào mảng
arr = np.append(arr, 60)
print(arr)

# Xóa đi một ví trí nào đó trong mảng
arr = np.delete(arr, 3)
print(arr)

[ 3 15  2 10 30 21 50 16]
[ 2  3 10 15 16 21 30 50]
[50 16  3]
[50 16  3 60]
[50 16  3]


In [5]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 61, 9],
                [7, 10, 8],
                [1, 21, 51]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[ 3  9 61]
 [ 7  8 10]
 [ 1 21 51]]
[[ 1 10  8]
 [ 3 21  9]
 [ 7 61 51]]


In [6]:
# Tạo một mảng 2D
arr = np.array([[1, 4, 7], [4, 8, 12]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [7]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1, 5, 7, 10, 15])
arr_float = arr.astype(float)
print(arr_float)

[ 1.  5.  7. 10. 15.]


In [8]:
# Thay đổi hình dạng của mảng
arr = np.array([1, 6, 3, 4, 2, 9])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 6 3]
 [4 2 9]]
[[1 6]
 [3 4]
 [2 9]]


In [9]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

[1 6 3 4 2 9]


In [10]:
# Cắt lát mảng
arr = np.array([1, 6, 9, 10, 15])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) 

sub_arr = arr[:-1] 
print(sub_arr)

sub_arr = arr[-2:]  
print(sub_arr)

[ 6  9 10]
[ 1  6  9 10]
[10 15]


In [11]:
# Chuyển vị mảng
arr = np.array([[1, 2, 4], [4, 9, 16]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[ 1  2  4]
 [ 4  9 16]]
[[ 1  4]
 [ 2  9]
 [ 4 16]]


In [12]:
# Nối mảng
arr1 = np.array([1, 4, 7])
arr2 = np.array([12, 15, 16])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 1  4  7 12 15 16]


In [13]:
# II. Hàm tính tổng (Sum)
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([3, 4, 9, 10, 15])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# III. Hàm tính trung bình (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# IV. Hàm tìm giá trị lớn nhất và nhỏ nhất (Max và Min)
# - Hàm numpy.max() và numpy.min() dùng để tìm giá trị lớn nhất và nhỏ nhất trong mảng.
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([1, 4, 6])
arr2 = np.array([8, 12, 16])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 41
Giá trị trung bình của mảng arr: 8.2
Giá trị lớn nhất trong mảng arr: 15
Giá trị nhỏ nhất trong mảng arr: 3
Độ lệch chuẩn của mảng arr: 4.354308211415448
Phương sai của mảng arr: 18.96
Tổng tích chập của arr1 và arr2: 152
